### ISSUE TITLE
Failing to start the admin server

### ISSUE THREAD

**Issue by shivajid** [google/saxml#10]
Getting the following error

1110 03:19:42.630464 1622013 admin_server.go:54] Failed to start server: config.Load error: Get "https://storage.googleapis.com/storage/v1/b/sax-data2/o/sax-root%2Fsax%2Ftest%2FMETADATA?alt=json&prettyPrint=false&projection=full": context canceled
goroutine 1 [running]:
github.com/golang/glog.stacks(0x0)
	external/com_github_golang_glog/glog.go:769 +0x89
github.com/golang/glog.(*loggingT).output(0x101ba60, 0x3, 0xc0003038f0, {0xcf565f?, 0xc0002dfef8?}, 0x1?, 0x0)
	external/com_github_golang_glog/glog.go:720 +0x46d
github.com/golang/glog.(*loggingT).printf(0xc000081920?, 0xbfa6d8?, {0xb206b6, 0x1a}, {0xc0002dfef8, 0x1, 0x1})
	external/com_github_golang_glog/glog.go:655 +0x10f
github.com/golang/glog.Fatalf(...)
	external/com_github_golang_glog/glog.go:1148
main.main()
	saxml/bin/admin_server.go:54 +0x273

**Comment by shivajid** [comment]
This is resolved.
